apiVersion: v1
kind: Namespace
metadata:
  name: ceph

---
apiVersion: v1
kind: Secret
type: kubernetes.io/rbd
metadata:
  name: ceph-secret-admin
  namespace: ceph
data:
  key: {{ base64 .Secrets.ClientAdminKey }}

---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-conf-combined
  namespace: ceph
type: Opaque
data:
  ceph.conf: {{ base64 .Secrets.CephConf }}
  ceph.client.admin.keyring: {{ base64 .Secrets.ClientAdminKeyring }}
  ceph.mon.keyring: {{ base64 .Secrets.MonKeyring }}

---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-bootstrap-rgw-keyring
  namespace: ceph
type: Opaque
data:
  ceph.keyring: {{ base64 .Secrets.RGWBootstrapKeyring }}

---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-bootstrap-mds-keyring
  namespace: ceph
type: Opaque
data:
  ceph.keyring: {{ base64 .Secrets.MDSBootstrapKeyring }}

---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-bootstrap-osd-keyring
  namespace: ceph
type: Opaque
data:
  ceph.keyring: {{ base64 .Secrets.OSDBootstrapKeyring }}

---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-bootstrap-rbd-keyring
  namespace: ceph
type: Opaque
data:
  ceph.keyring: {{ base64 .Secrets.RBDBootstrapKeyring }}

---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-client-admin-keyring
  namespace: ceph
type: Opaque
data:
  ceph-client-key: {{ base64 .Secrets.ClientAdminKeyring }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-config
  namespace: ceph
data:
  config: |
{{.Kube.AdminConf | indent 8}}
