apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-endpoints
  namespace: glusterfs
subsets:
  - addresses:
      {{ range .Deploys }}
      - ip: {{ .Node.Host }}
      {{ end }}
    ports:
      - port: 24007

---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-endpoints
  namespace: glusterfs
spec:
  ports:
    - port: 24007