{{ if .Heketi.Enable }}

kind: Service
apiVersion: v1
metadata:
  name: heketi
  namespace: glusterfs
  labels:
    glusterfs: heketi-service
    heketi: service
  annotations:
    description: Exposes Heketi Service
spec:
  clusterIP: {{.Heketi.VIP}}
  selector:
    glusterfs: heketi-pod
  ports:
    - name: heketi
      port: 8080
      targetPort: 8080

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: heketi
  namespace: glusterfs
  labels:
    glusterfs: heketi-deployment
    heketi: deployment
  annotations:
    description: Defines how to deploy Heketi
spec:
  replicas: {{.Heketi.Replicas}}
  selector:
    matchLabels:
      glusterfs: heketi-pod
      heketi: pod
  template:
    metadata:
      name: heketi
      labels:
        glusterfs: heketi-pod
        heketi: pod
    spec:
      serviceAccountName: heketi-service-account
      {{ if gt (len .Heketi.NodeSelector) 0 }}
      nodeSelector:
        {{ range $key, $value := .Heketi.NodeSelector }}
        {{ $key }}: {{ $value }}{{ end }}
      {{ end }}
      containers:
        - image: {{.Repo}}heketi/heketi:dev
          imagePullPolicy: IfNotPresent
          name: heketi
          env:
            - name: HEKETI_USER_KEY
              value: {{ .Heketi.UserKey }}
            - name: HEKETI_ADMIN_KEY
              value: {{ .Heketi.AdminKey }}
            - name: HEKETI_EXECUTOR
              value: "kubernetes"
            - name: HEKETI_FSTAB
              value: "/var/lib/heketi/fstab"
            - name: HEKETI_SNAPSHOT_LIMIT
              value: '14'
            - name: HEKETI_KUBE_GLUSTER_DAEMONSET
              value: "y"
            - name: HEKETI_IGNORE_STALE_OPERATIONS
              value: "true"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: db
              mountPath: "/var/lib/heketi"
            - name: config
              mountPath: /etc/heketi
            - name: topology-json
              mountPath: /data
          readinessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 3
            httpGet:
              path: "/hello"
              port: 8080
          livenessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 30
            httpGet:
              path: "/hello"
              port: 8080
      volumes:
        - name: db
          glusterfs:
            endpoints: glusterfs-endpoints
            path: heketidbstorage
        - name: config
          secret:
            secretName: heketi-config-secret
        - name: topology-json
          configMap:
            name: heketi-config-topology-json
{{ end }}